services:
  firefox-sync-bridge:
    build:
      context: .
    container_name: firefox-sync-bridge
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/firefox-sync-bridge:/config
    environment:
      - BRIDGE_CONFIG=/config/config.json
